- name: Install OMP
  ansible.builtin.shell: curl -fsSL https://omp.sh/install | sh -s -- --binary
  become_user: "{{ admin_user }}"
  environment:
    HOME: "/home/{{ admin_user }}"
  args:
    creates: "/home/{{ admin_user }}/.local/bin/omp"
  when: not ansible_check_mode

- name: Link OMP command
  ansible.builtin.file:
    src: "/home/{{ admin_user }}/.local/bin/omp"
    dest: /usr/local/bin/omp
    state: link
  when: not ansible_check_mode
