- name: Install Docker
  ansible.builtin.shell: curl -fsSL https://get.docker.com | sh
  args:
    creates: /usr/bin/docker

- name: Add admin user to Docker group
  ansible.builtin.user:
    name: "{{ admin_user }}"
    groups: docker
    append: true
